name: Check ebook

on:
  workflow_run:
    workflows: [Render and Publish]
    types:
      - completed

jobs:
  check-epub:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with: 
          ref: gh-pages

      - name: Install epubcheck
        run: sudo apt-get install epubcheck
    
      - name: Check the epub
        run: epubcheck Reproducible-Polyglot-Data-Science.epub
